#!/bin/sh -ex
# vim:se sw=2 ts=2 sts=2 et ai:
# Script to build nanoBoot

# Leonardo/Nano compatible board
#   -- LED is ON with ATmega32u4 PIN C7 HIGH
# #define LED_BIT           7
# #define LED_CONF          DDRC
# #define LED_PORT          PORTC
# #define LED_ACTIVE_LEVEL  1
DEFS="LEDDEFS=-DLED_ENABLED -DLED_BIT=7 -DLED_CONF=DDRC -DLED_PORT=PORTC -DLED_ACTIVE_LEVEL=1"

# Pro Micro compatible board
#   -- LED is ON with ATmega32u4 PIN B3 LOW
# #define LED_BIT           3
# #define LED_CONF          DDRB
# #define LED_PORT          PORTB
# #define LED_ACTIVE_LEVEL  0
#DEFS="LEDDEFS=\"-DLED_ENABLED -DLED_BIT=3 -DLED_CONF=DDRB -DLED_PORT=PORTB -DLED_ACTIVE_LEVEL=0\""

make clean
make "$DEFS"
mv -f nanoBoot.hex nanoBoot-leonardo.hex


